## Lagrange interpolation

In [1]:
from datetime import datetime as dt
import numpy as np
import sympy as smp
from sympy import symbols,simplify
x=np.array([1,2,3])
y=np.array([12,16,18])
d=symbols('d')
p=0
itime=dt.now()
for i in range(len(x)):
    z=1
    for j in range(len(y)):
        if i!=j:
            z=z*(d-x[j])/(x[i]-x[j])
    p=p+z*y[i]
m=smp.lambdify(d,p)
print('ans\n',simplify(p),'\n',m(3))
ftime=dt.now()
print("The cost of computation is ",ftime-itime)


ans
 -d**2 + 7*d + 6 
 18.0
The cost of computation is  0:00:00.420151


# 2nd way 

In [2]:

x=np.array([1,2,3,4,5])
y=np.array([2,4,6,8,10])
d=symbols('d')
b=0
i=1
itime=dt.now()
while i<len(x):
    z=1
    for j in range(len(x)):
        if i != j:
            z=z*(d-x[j])/(x[i]-x[j])
    b+=y[i]*z
    i+=1
    n=smp.lambdify(d,b)
print(simplify(b),"\n",n(3))
ftime=dt.now()
print("The cost of computation is ",ftime-itime)

-d**4/12 + 7*d**3/6 - 71*d**2/12 + 89*d/6 - 10 
 6.0
The cost of computation is  0:00:00.081049


## NEWTON DIVIDED DIFFERENCE INTERPOLATION

In [3]:
import numpy as np
import sympy as smp
from sympy import symbols

x= np.array([1,2,4])
y=np.array([8,68,123])
z=3.5
itime=dt.now()
rslt= np.zeros([len(x),len(x)+1])
for k in range(len(x)):
    rslt[k][0]=rslt[k][0]+x[k]
    rslt[k][1]=rslt[k][1]+y[k]
j=2
a=len(x)-1
p=symbols('p')
while j<len(x)+1:
    i=0
    k=j-1
    while i<a:
        d=rslt[i+k][0]-rslt[i][0]
        rslt[i][j]=rslt[i][j]+((rslt[i+1][j-1]-rslt[i][j-1])/d)
        i+=1
    a-=1
    k+=1
    j+=1
print(f'The table with col1 as x and col2 and function \n',rslt,'\n')
j=1
sum=0
while (j<len(x)+1):
    partition=rslt[0][j]
    i=0
    while i<j-1:
        partition = partition*(p-x[i])
        i+=1
    sum+=partition
    j+=1
print('The required polynomial is\n',simplify(sum),'\n')
poly=smp.lambdify(p,sum)
print(f'The value of polynomial at {z} is \n',poly(z))
ftime=dt.now()
print("The cost of computation is ",ftime-itime)



The table with col1 as x and col2 and function 
 [[  1.           8.          60.         -10.83333333]
 [  2.          68.          27.5          0.        ]
 [  4.         123.           0.           0.        ]] 

The required polynomial is
 -10.8333333333333*p**2 + 92.5*p - 73.6666666666667 

The value of polynomial at 3.5 is 
 117.37500000000011
The cost of computation is  0:00:00.028687


# forward interpolation

In [4]:

import numpy as np
import sympy as smp
from sympy import symbols,simplify,lambdify,factorial,Eq,solve
d=symbols('d')
r=int(input("number of points : "))
x=[]
a=float(input("enter first absissa : "))
h=float(input("enter the difference: "))
q=float(input('enter the point where you want the poly value '))
for i in range(r):
        c=a+i*h
        x.append(c)
print(x)
itime=dt.now()
D=np.zeros((r,r))
for i in range(r):
        D[i][0]=float(input('enter the ordinate element : '))
for j in range(1,r+1):
        for i in range(0,r-j):
                D[i][j]=D[i+1][j-1]-D[i][j-1]
print(D)
s=1
m=0
for i in range (r):
        t=0
        if q<=x[i]:
                t=i
                break
print(t)
u=symbols('u')
eqq=Eq(x[t-1]+h*u,q)
o=solve(eqq)
for i in range(0,r):
        c=1
        for j in range(0,i):
                c=c*(d-j)
        m+=(c*D[t-1][i])/(factorial(i))
n=smp.lambdify(d,m)
print(u,'\n',m,'\n',n(o[0]))
ftime=dt.now()
print("The cost of computation is ",ftime-itime)



[0.0, 2.0, 4.0, 6.0, 8.0]
[[ 12.  11.  11. -11.  11.]
 [ 23.  22.   0.   0.   0.]
 [ 45.  22.   0.   0.   0.]
 [ 67.  22.   0.   0.   0.]
 [ 89.   0.   0.   0.   0.]]
2
u 
 22.0*d + 23.0 
 34.0000000000000
The cost of computation is  0:00:10.485565


# backward interpolation

In [5]:


import numpy as np
import sympy as smp
from sympy import symbols,simplify,lambdify,factorial,Eq,solve
d=symbols('d')
r=int(input("number of points : "))
q=float(input('enter the point where you want the poly value '))
x=[]
a=float(input("enter first absissa : "))
h=float(input("enter the difference: "))
for i in range(r):
        c=a+i*h
        x.append(c)
print(x)
itime=dt.now()
D=np.zeros((r,r))
for i in range(r):
        D[i][0]=float(input('enter the ordinate element : '))
for j in range(1,r+1):
        for i in range(j,r):
               D[i][j]=D[i][j-1]-D[i-1][j-1]
print(D)
s=1
m=0
for i in range (r):
        t=0
        if q<=x[i]:
                t=i
                break
u=symbols('u')
eqq=Eq(x[t]+h*u,q)
o=solve(eqq)
for i in range(0,r):
        c=1
        for j in range(0,i):
                c=c*(d+j)
        m+=(c*D[t][i])/(factorial(i))
n=smp.lambdify(d,m)
print(m,'\n',n(o[0]))
ftime=dt.now()
print("The cost of computation is ",ftime-itime)


[3.0, 5.0, 7.0, 9.0, 11.0, 13.0]
[[ 23.   0.   0.   0.   0.   0.]
 [ 45.  22.   0.   0.   0.   0.]
 [ 67.  22.   0.   0.   0.   0.]
 [ 92.  25.   3.   3.   0.   0.]
 [105.  13. -12. -15. -18.   0.]
 [150.  45.  32.  44.  59.  77.]]
22.0*d + 45.0 
 45.0000000000000
The cost of computation is  0:00:13.648539
